# Generated by Django 4.0.4 on 2022-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='desciption',
            new_name='description',
        ),
    ]
