# Generated by Django 4.0.4 on 2022-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_desciption_expenses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
