# Generated by Django 4.0.4 on 2022-09-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenses_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-creation_date']},
        ),
    ]
