# Generated by Django 4.0.4 on 2022-09-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_category_income_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-creation_date']},
        ),
    ]
